### ISSUE TITLE
CSP Spot Check #1 (database, postman, cookies)

### ISSUE THREAD

**Issue by jplip** [jplip/justin2.0#2]
Justin Liporada
[Questions Below](https://github.com/jplip/justin2.0/issues/2#issuecomment-1921898950)

**Comment by jplip** [comment]
Issue Heading
 Name, Period, Score. (John Mortensen, P2, 1..75)
 All Scores (e.g. Q1: 8.5, Q2: 9, Q3: 5.5)
 Top 4 Score Total (e.g. Q1: 8.5 + Q2: 9 = 1.75 of 2.0 )
New Comment in Issue
 Question 1: database, with database schema change
 Record Check Marks
 Provide Screen Capture(s)
New Comment in Issue
 Question 2: postman with /authentication screen
 Record Check Marks
 Provide Screen Capture(s)
New Comment in Issue
 Question 3: postman with /api screen to access data under authentication
 Record Check Marks
 Provide Screen Capture(s)

**Comment by jm1021** [comment]
I remember our conversations and scores.  Very well done in time frame.   The only thing that would make this nicer is if it were 3 comments instead of one with scores at the top of each.

**Comment by jplip** [comment]
# Q1: database, with database schema change
**Score .95**

- [x] Show db.Column changes you have made to model/python file in Visual Studio Code
<img width="550" alt="Screen Shot 2024-01-31 at 11 30 30 AM" src="https://github.com/jplip/justin2.0/assets/142539012/1f657992-404e-4e0f-a23b-2cabc3e9d6f7">

- [x] Show initialization data code in VSCode
- [x] Demo delete database and run ./migrate.sh
- [x] Demo corresponding schema change in SQLite3
- [x] Demo initialization data captured in Column in SQLite3

**Comment by jplip** [comment]
# Q2: postman with /authentication screen
**Score .9**

- [x] Show /authenticate endpoint code in Visual Studio Code
<img width="509" alt="Screen Shot 2024-01-31 at 11 40 10 AM" src="https://github.com/jplip/justin2.0/assets/142539012/f8e09127-9169-41ec-bd1e-ee3d85f9f291">

- [x] Show and Demo /authenticate in Postman…
- [x] Demo calling to endpoint
- [x] Show JSON data passed in call
<img width="613" alt="Screen Shot 2024-01-31 at 11 41 42 AM" src="https://github.com/jplip/justin2.0/assets/142539012/6fbd1d10-abe2-41e9-adb8-9070a7436a1b">

- [x] Show Response window
<img width="648" alt="Screen Shot 2024-01-31 at 11 38 53 AM" src="https://github.com/jplip/justin2.0/assets/142539012/3f3d5238-4a19-4e33-9607-931ff4892c63">

- [x] Show Cookie acquired window
<img width="815" alt="Screen Shot 2024-01-31 at 11 35 48 AM" src="https://github.com/jplip/justin2.0/assets/142539012/034255be-83d5-41da-b71a-127a1c4c581d">

- [x] Cut/Copy/Paste Cookie into [jwt.io](http://jwt.io/) and show decrypting payload
<img width="1266" alt="Screen Shot 2024-01-31 at 11 37 38 AM" src="https://github.com/jplip/justin2.0/assets/142539012/2709a042-6bf9-4890-8a1f-ebc26e3df780">

**Comment by jplip** [comment]
# Q3: postman with /api screen to access data under authentication
**Score .9**

- [x] Show /api CRUD code in Visual Studio Code, expecting READ/GET code
<img width="348" alt="Screen Shot 2024-01-31 at 11 46 46 AM" src="https://github.com/jplip/justin2.0/assets/142539012/d72ea98d-f57b-419c-b57e-4a0ee1077141">

- [x] Show and Demo /api READ/GET endpoint in Postman…
- [x] Demo calling to endpoint that requires Cookie
- [x] Show Response/Data
<img width="648" alt="Screen Shot 2024-01-31 at 11 38 53 AM" src="https://github.com/jplip/justin2.0/assets/142539012/dacfcdc1-bfe4-4678-87f1-0a6cf3f96441">

- [x] Demo Deleting cookie
- [x] Demo calling endpoint again
- [x] Show Response/Failure
<img width="532" alt="Screen Shot 2024-01-31 at 1 28 22 PM" src="https://github.com/jplip/justin2.0/assets/142539012/100b5831-f94a-489f-a253-33d193c12dfc">
