### ISSUE TITLE
Debugging Review

### ISSUE THREAD

**Issue by jplip** [jplip/justin2.0#6]
## Debugging/Tracing code...
***Build a code debugging blog using this as a guideline. Be sure to read canvas to optimize opportunities for points.***

### 1. Start backend using Debugging
<img width="286" alt="Screen Shot 2024-03-05 at 10 53 25 AM" src="https://github.com/jplip/justin2.0/assets/142539012/0475da4e-b9a7-48a3-b244-c80d3c9d09e8">

### 2. Set break point at the beginning of endpoint code
<img width="717" alt="Screen Shot 2024-03-06 at 10 22 23 PM" src="https://github.com/jplip/justin2.0/assets/142539012/d0113d93-fff6-43f1-9bd7-682da516898c">
<br>Looking for why my login doesn't work and can't sign in.

### 3. Start in frontend with split screen loading source for an API fetch using GET.
<img width="1440" alt="Screen Shot 2024-03-06 at 10 29 27 PM" src="https://github.com/jplip/justin2.0/assets/142539012/ca715bf1-4d82-4de5-8350-6e88f2265778">

### 4. Set break point on fetch, inside .then, inside .fetch
<img width="1439" alt="Screen Shot 2024-03-07 at 10 11 36 PM" src="https://github.com/jplip/justin2.0/assets/142539012/f912ff3f-5770-45c8-bd6d-855085ea5221">
<br>Set break points in the frontend as well to catch the fetch issues.

### 5. Run frontend, screen capture break at fetch while examining Body
<img width="1440" alt="Screen Shot 2024-03-07 at 10 06 57 PM" src="https://github.com/jplip/justin2.0/assets/142539012/ff73df75-b47a-4b5d-a56a-2705d9a9ccf8">

### 6. Press play on frontend, observe stop inside of backend
<img width="720" alt="Screen Shot 2024-03-06 at 10 36 29 PM" src="https://github.com/jplip/justin2.0/assets/142539012/d258b779-7a27-4e43-9522-aa9e7ca643db">

### 7. Press step over on backend until you have obtained data from database, screen capture Python Object
<img width="451" alt="Screen Shot 2024-03-06 at 10 37 13 PM" src="https://github.com/jplip/justin2.0/assets/142539012/fee04f55-d10f-4d46-918d-7a86dcd55997">
<br>Looking at the user data that is inputed from the frontend to the backend.

### 8. Press play button to end backend debugging session.
<img width="725" alt="Screen Shot 2024-03-06 at 10 37 42 PM" src="https://github.com/jplip/justin2.0/assets/142539012/8f1d9c6d-259b-441b-bdd2-95b2b85f8657">
<br>The problem is the user or password.
<img width="1440" alt="Screen Shot 2024-03-06 at 10 38 13 PM" src="https://github.com/jplip/justin2.0/assets/142539012/5fef7177-f870-4d66-a93d-fd7f5dca848e">

### 9. Return to frontend debug session
<img width="1439" alt="Screen Shot 2024-03-06 at 10 40 56 PM" src="https://github.com/jplip/justin2.0/assets/142539012/3be9028e-5c28-4ae5-94ba-8f3aea12421a">

### 10. Step in until you see data, screen capture capturing break point and Data.

<img width="635" alt="Screen Shot 2024-03-11 at 10 19 53 AM" src="https://github.com/jplip/justin2.0/assets/142539012/2d33c7d4-5674-4c42-b8af-66ca11020d35">
<br>Knowing the problem, I figure out the name or password is wrong and change the username.
<img width="496" alt="Screen Shot 2024-03-11 at 10 22 18 AM" src="https://github.com/jplip/justin2.0/assets/142539012/f821a6bb-942a-4d6a-a382-9004d0ac501b">
<br>It works and problem was user id. This then redirects to the update page of all accounts in the database.
<img width="762" alt="Screen Shot 2024-03-11 at 10 22 57 AM" src="https://github.com/jplip/justin2.0/assets/142539012/fd15425a-f1d1-4a26-8122-95f45139c6e6">

**Comment by jplip** [comment]
Quick Grading for Seed (indi, team), and Debugging
To optimize initializing seed and foster pair/team collaboration...

1. Make these assignments into a team and individual blogging project
2. Plan the best way to meet Seed individual and team goals
3. Plan how to fit debugging into "key deliverables" according to canvas descriptions
4. Learn about each others projects, perform analysis on how each has met or needs to meet requirements
5. Prepare and work through this as a team, and do it by end of Thursday, ready for Friday speed review as a team
6. Remember to be honest in each assessment, as growth mindset and honesty will be key to learning

**Comment by jm1021** [comment]
Good sequence of steps.  Good illustrations at showing data.   Perhaps a little more clarity on which line you were at when you shared the data.

**Comment by iKAN2025** [comment]
1.85 Sequence of Steps/Everything Completed Had stuff working

**Comment by Lin-cT** [comment]
I like that it clearly shows the images and body, and I am able to follow through the steps. Very concise, but I feel like some extra comments talking about the code would have been nice. 

1.85/2.0
